# Generated by Django 3.2.9 on 2021-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nunber', models.IntegerField(default=0)),
                ('postal_code', models.TextField()),
            ],
        ),
    ]
