# Generated by Django 3.2.9 on 2021-11-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
    ]
