# Generated by Django 3.2.9 on 2021-11-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.TextField(default='L'),
        ),
    ]
